apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bootcampapp-75gf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bootcampapp-75gf
    app.kubernetes.io/part-of: my-app-quarkus2
  name: bootcampapp-75gf
  namespace: eyuen-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: bootcampapp-75gf
status:
  loadBalancer: {}
